version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-208-118.compute-1.amazonaws.com
            database: dcg74g8nbi98kc
            ssl: true
            user: jurifcizeowlhu
            password: f47dcd670329a5a6f6c38cb2dc0b663b4a5bc40280fc5c88a5bf4e70709096e4
            rawAccess: true
            port: '5432'
            migrations: true
